# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menderLoginGUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(52, 122, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 122, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 122, 135))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 40, 220, 72))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("mender_logo.png"))
        self.label.setObjectName("label")
        self.usr = QtWidgets.QLineEdit(self.centralwidget)
        self.usr.setGeometry(QtCore.QRect(230, 225, 180, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usr.sizePolicy().hasHeightForWidth())
        self.usr.setSizePolicy(sizePolicy)
        self.usr.setStatusTip("")
        self.usr.setInputMask("")
        self.usr.setMaxLength(128)
        self.usr.setObjectName("usr")
        self.pwd = QtWidgets.QLineEdit(self.centralwidget)
        self.pwd.setGeometry(QtCore.QRect(230, 280, 180, 30))
        self.pwd.setStatusTip("")
        self.pwd.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.pwd.setMaxLength(256)
        self.pwd.setFrame(True)
        self.pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwd.setObjectName("pwd")
        self.logInBtn = QtWidgets.QPushButton(self.centralwidget)
        self.logInBtn.setGeometry(QtCore.QRect(355, 355, 70, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.logInBtn.setPalette(palette)
        self.logInBtn.setObjectName("logInBtn")
        self.quitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.quitBtn.setGeometry(QtCore.QRect(215, 355, 70, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.quitBtn.setPalette(palette)
        self.quitBtn.setCheckable(False)
        self.quitBtn.setChecked(False)
        self.quitBtn.setAutoRepeat(False)
        self.quitBtn.setDefault(False)
        self.quitBtn.setFlat(False)
        self.quitBtn.setObjectName("quitBtn")
        self.server_addr = QtWidgets.QLineEdit(self.centralwidget)
        self.server_addr.setEnabled(True)
        self.server_addr.setGeometry(QtCore.QRect(230, 150, 180, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.server_addr.sizePolicy().hasHeightForWidth())
        self.server_addr.setSizePolicy(sizePolicy)
        self.server_addr.setStatusTip("")
        self.server_addr.setInputMask("")
        self.server_addr.setMaxLength(256)
        self.server_addr.setFrame(False)
        self.server_addr.setReadOnly(True)
        self.server_addr.setClearButtonEnabled(False)
        self.server_addr.setObjectName("server_addr")
        self.domain_label = QtWidgets.QLabel(self.centralwidget)
        self.domain_label.setGeometry(QtCore.QRect(230, 137, 100, 14))
        self.domain_label.setObjectName("domain_label")
        self.serverCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.serverCheckBox.setGeometry(QtCore.QRect(290, 180, 120, 16))
        self.serverCheckBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.serverCheckBox.setObjectName("serverCheckBox")
        self.showPwd = QtWidgets.QCheckBox(self.centralwidget)
        self.showPwd.setGeometry(QtCore.QRect(260, 308, 150, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showPwd.sizePolicy().hasHeightForWidth())
        self.showPwd.setSizePolicy(sizePolicy)
        self.showPwd.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.showPwd.setObjectName("showPwd")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 32))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mender User Log In"))
        self.usr.setPlaceholderText(_translate("MainWindow", "User name"))
        self.pwd.setPlaceholderText(_translate("MainWindow", "Password"))
        self.logInBtn.setText(_translate("MainWindow", "Log in"))
        self.quitBtn.setText(_translate("MainWindow", "Quit"))
        self.server_addr.setPlaceholderText(_translate("MainWindow", "https://hosted.mender.io/"))
        self.domain_label.setText(_translate("MainWindow", "Server address"))
        self.serverCheckBox.setText(_translate("MainWindow", "Custom server"))
        self.showPwd.setText(_translate("MainWindow", "Show password"))

